{
 "title": "SNP TEMPS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PROC DATA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
     "options": {
      "content": "<div style=\"text-align: center; font-weight: bold;\">\n  PROC A - FPGA 1\n</div>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 6, "y": 1 },
     "options": {
      "content": "<div style=\"text-align: center; font-weight: bold;\">\n  PROC B - FPGA 2\n</div>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 12, "y": 1 },
     "options": {
      "content": "<div style=\"text-align: center; font-weight: bold;\">\n  PROC C - FPGA 3\n</div>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 5, "x": 18, "y": 1 },
     "options": {
      "content": "<div style=\"text-align: center; font-weight: bold;\">\n  PROC D - FPGA 4\n</div>"
     }
    },
    {
     "title": "TEMPS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_temp{component=\"fpga_1\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TEMPS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_temp{component=\"fpga_2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TEMPS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_temp{component=\"fpga_3\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TEMPS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_temp{component=\"fpga_4\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"config_bw_25G_A\", way=\"tx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"config_bw_25G_B\", way=\"tx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"config_bw_25G_C\", way=\"tx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"config_bw_25G_D\", way=\"tx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"config_bw_25G_A\", way=\"rx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"config_bw_25G_B\", way=\"rx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"config_bw_25G_C\", way=\"rx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RX",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"config_bw_25G_D\", way=\"rx\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SNP PTP STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNP PTP DATA",
     "type": "table",
     "gridPos": { "h": 4, "w": 20, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "snp_ptp_status_all{ptpMasterIP=\"2.2.2.2\"}"
      }
     ]
    },
    {
     "title": "PTP Master Delay",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_ptp_status{component=\"ptp_master_delay\"}"
      }
     ]
    },
    {
     "title": "PTP Master Offset",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_ptp_status{component=\"ptp_master_offset\"}"
      }
     ]
    },
    {
     "title": "PTP STATE",
     "type": "stat",
     "description": "Unit Locked to PTP",
     "gridPos": { "h": 6, "w": 8, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_ptp_status_all{ptpCtlrState=\"Locked\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SNP WAN PRIMARY STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAN PRIMARY",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "snp_wan_status_primary{priIpAddr=\"192.168.61.23\"}"
      }
     ]
    },
    {
     "title": "PRIMARY WAN ERRORS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"errs\", network=\"primary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PRIMARY WAN ERRORS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 10, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"over_bandwidth\", network=\"primary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP WAN PRIMARY RX PACKETS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"pkts\", network=\"primary\", way=\"rx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP WAN PRIMARY RX PACKETS",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"rate\", network=\"primary\", way=\"rx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP WAN PRIMARY TX PACKETS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 4 },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"pkts\", network=\"primary\", way=\"tx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP WAN PRIMARY TX PACKETS",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"rate\", network=\"primary\", way=\"tx\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SNP WAN SECONDARY STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAN PRIMARY",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "snp_wan_status_secondary{secIpAddr=\"192.168.71.23\"}"
      }
     ]
    },
    {
     "title": "SECONDARY WAN ERRORS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"errs\", network=\"secondary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP WAN SECONDARY RX ERRORS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 10, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"over_bandwidth\", network=\"primary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP WAN SECONDARY RX PACKETS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"pkts\", network=\"secondary\", way=\"rx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP WAN SECONDARY RX PACKETS",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"rate\", network=\"secondary\", way=\"rx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP WAN SECONDARY TX PACKETS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"pkts\", network=\"secondary\", way=\"tx\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP WAN SECONDARY TX PACKETS",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_wan_status{component=\"rate\", network=\"secondary\", way=\"tx\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SNP UNIT TEMPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNP MAIN BOARD TEMPS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_temp{alarmType=\"board_temp\", component=\"main_board\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP IO BOARD TEMPS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_temp{alarmType=\"board_temp\", component=\"io_board\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP QSFP PRIMARY TEMPS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_temp{alarmType=\"qsfp_temp\", component=\"qsfp_primary\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SNP QSFP SECONDARY TEMPS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_temp{alarmType=\"qsfp_temp\", component=\"qsfp_secondary\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SNP FAN SPEED RPM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "FAN 1",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_speed{component=\"front_fan_1\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAN 2",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_speed{component=\"front_fan_2\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAN 3",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_speed{component=\"front_fan_3\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FAN 4",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 18, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "snp_system_status_hw_speed{component=\"front_fan_4\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "PRIMARY QSFP DATA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Primary QSFP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{alarmType=\"qsfp_present\", network=\"primary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary QSFP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{alarmType=\"qsfp_dataValid\", network=\"primary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QSFP PRIMARY TX DBm",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{alarmType=\"qsfp_power\", network=\"primary\", way=\"tx\"}"
    }
   ]
  },
  {
   "title": "QSFP PRIMARY VENDOR DETAILS",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{vendor_name=\"INNOLIGHT       \", network=\"primary\"}"
    }
   ]
  },
  {
   "title": "QSFP PRIMARY RX DBm",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{alarmType=\"qsfp_power\", network=\"primary\", way=\"rx\"}"
    }
   ]
  },
  { "title": "SECONDARY QSFP DATA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Secondary QSFP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{alarmType=\"qsfp_present\", network=\"secondary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secondary QSFP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{alarmType=\"qsfp_dataValid\", network=\"secondary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QSFP SECONDARY TX DBm",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{alarmType=\"qsfp_power\", network=\"secondary\", way=\"tx\"}"
    }
   ]
  },
  {
   "title": "QSFP SECONDARY VENDOR DETAILS",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 22 },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{vendor_name=\"INNOLIGHT       \", network=\"secondary\"}"
    }
   ]
  },
  {
   "title": "QSFP SECONDARY RX DBm",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "snp_system_status_qsfp{alarmType=\"qsfp_power\", network=\"secondary\", way=\"rx\"}"
    }
   ]
  }
 ]
}